### ISSUE TITLE
Smiliar Movie

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#116]
Hey Charlie,

I think it would be a great thing to have a widget or shortcode showing similar movies to the actual movie. ;)

Mario

**Comment by kutluhanaykut** [comment]
I also am trying to make something like this.. Since i am not so great at sql i am having issues (huge sql processes) but the similarities seems cool now.. Checkout benzerfilmler.com

One question about that i couldnt be able to execute my plugin after your movie display which is a must for me because i want to display selected movie info then the similar movies..

And.. I may discuss my similarity algorithm with you over e-mail since i want to keep it a bit secret, at least at the moment..
