### ISSUE TITLE
Images and posters bug

### ISSUE THREAD

**Issue by skechboy** [wpmovielibrary/wpmovielibrary#239]
Hi,

I'm experiencing some weird behavior in the Images and Posters tab. The first thing is that when I go to some movie to add poster in the Posters tab I get only blank page. I don't know if this is bug or normal behavior if there is no poster available because in some previous issues here I've noticed that there is lack of support for adding own images, something which trows me to another bug. 

When I go to the images tab i clearly can see "Load images" section  and it works great when it can find pictures for the corresponding movie, but if there isn't images for that movie it shows No items found, drop files... or select files. So when I Upload image it all goes well the image is uploaded successfully ( i can confirm this by watching the output from async-upload.php which is {"success":true,"data":{"id":61,"title".... and also the uploaded image can be found in uploads directory ) however from some unknown reason the "Import images" button is still frozen and I'm not able to import the image.

The other weird thing that I've noticed with the images tab is when I add images that are automatically fetched there is no button to remove them ( perhaps this is part of the same bug ). The weird thing is my intuition was telling me to go over the image and perhaps delete button will be shown somewhere but nothing appeared and i decided perhaps a click will remove the image, but instead of that it just redirected me to editing the same movie again. Later I've noticed that all images parent anchors have the same data-href attribute "/wp-admin/post.php?post=POST_ID&amp;action=edit"

3 very strange bugs that are making me big difficultly, no error logs related with the plugin are shown on the server side, neither on the client side in developer tools.

Here is my system information https://gist.github.com/skechboy/0bfd415fafae29548250

What can be the cause for this? Perhaps it is something related with my installation? 

Thanks

**Comment by CaerCam** [comment]
Hi Trajche,

Actually these are more like misconceptions than bugs! The Posters blank tab is most likely the fact that you only have one single poster imported for each movie; that tab shows the posters already imported, but right now the plugin can't handle multiple posters download. That will be fixed in version 2.2.

About the images import, the plugin in its current can not handle custom images import; you can upload images if no one is available for the current movie, but these images will not be linked to the movie. That the media modal behavior to fallback to the uploader if there's no media to show, by the time I developed that part I didn't find a way to prevent it. This will also be fixed with version 2.2 which changes a lot of things on the metabox and images/posters import parts.

And finally about the imported images, there is no delete button (but will be in version 2.2 :smile:) and indeed, the link is not working. I'll fix the link for version 2.1.4.

**Comment by skechboy** [comment]
Hi Charlie,

thanks for your response, do you have any schedule when version 2.2 will be released? Are some of these features are available in 2.2 branch? I hope in the v 2.2 we will be able to upload our posters and images regardless if there are images and posters available for download. 

Thanks

**Comment by CaerCam** [comment]
Yes, all dev on version 2.2 is done on the [2.2-dev branch](https://github.com/wpmovielibrary/wpmovielibrary/tree/2.2-dev). And yes, images/posters will be available regardless of the amount of available images/posters from TMDb :)
