### ISSUE TITLE
latest reviews

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#244]
Hey Charlie,

a short time ago we've discussed the question if it's possible to show the latest reviews (not movies in database) and you said difficult. :D  

I have an idea for that thing. Is it possible to add an extra checkbox which shows (rated?) and a date of the rating? Than it should be easy to sort the reviews after dates and we could have the latest ratings. :) 

Just an idea, but one of the greatest feauteres for now, I can imagine. ;)

Cheers,
Mario

**Comment by CaerCam** [comment]
Not going to put this in the core, and here's why.

It makes perfect sense to list the latest movies in a review website context, which is not what the plugin is basically built to handle. More and more I get request from features that are meant only for review, movie database or streaming website, and that's a problem because the plugin would lose coherence if all these requests where met. Storing rating dates should, however, be implemented in the Advanced Rating plugin which I'm still planning to build but that's on pause due to the overweight of work do be done on v2.1.x and 2.2. Not in the core, but planned anyways :)

That being said, this made me think of another possible way: post modified date. For any content WordPress stores the date of the latest modification. That's not exactly what you're asking, but it could be a nice thing to make it possible for movies to have their modified date updated whenever a metadata/detail is changed. I'll give it some thinking!
