### ISSUE TITLE
Featured image and poster

### ISSUE THREAD

**Issue by kevinphung** [wpmovielibrary/wpmovielibrary#250]
When I add a movie, featured image and poster are the same. If I change the featured image, the poster is changed too.
How to make them different?

**Comment by CaerCam** [comment]
Yes, when importing a movie the movie's poster is downloaded and set as featured image. If you importer another poster, it will be used as featured image instead of the previous poster. I'm not actually sure about what you're asking: what distinction do you make between poster and featured image?

Currently you can't import multiple poster as the poster download process is built upon the featured image; that's something that will change in version 2.2 where the metadata import process has been completely rewriten, allowing multiple posters import just like images.

**Comment by kevinphung** [comment]
If I set posters as featured images, the posters is crop, lost details and look bad.
![poster issue](https://cloud.githubusercontent.com/assets/11687862/6908954/96151eb2-d76b-11e4-8a4a-45fa27a6059f.jpg)

When i change featured image, at /movies/ section, thumb is stretched. 
![poster issue 2](https://cloud.githubusercontent.com/assets/11687862/6908993/f84be8ea-d76b-11e4-9e52-d3aa2a45a98b.jpg)

please advise.

**Comment by CaerCam** [comment]
No advice for now: the posters are indeed in portrait, and the grid is not meant to display landscape-mode thumbnails… We could always edit the templates and adjust CSS, but it would be temporary. I'll make sure version 2.1.5 will support both portrait- and landscape-mode, though.
