### ISSUE TITLE
Ideas of making the plugin even better

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#254]
Hey Charlie,

I've an great idea for the plugin; I think so. Wouldn't it be nice to add custom facts to a movie? Or custom Vids from YouTube/The Blog. I know the "main"-plugin hasn't finished and it's probably for a plugin for a plugin (pluginception ;)), but I wanna tell that. What do you think?

Cheers,
Mario

**Comment by CaerCam** [comment]
Actually, something I've had in mind for some time − and that could join what you're describing − is a plugin to allow people to easily add/remove additional data support. With version 2.2 the metabox will be easier to manipulate by plugins (adding/removing panels, etc); I'm thinking of a plugin that would make it possible, using a dedicated section in the Settings panel, to add custom panels to the metabox and custom data fields.

That's a long shot, though. First because it needs version 2.2 to be out and alive, and second because it will take some time to build properly, time I don't have right now and won't have for a while… A good idea, still :)
