### ISSUE TITLE
issue with translation

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#256]
Hey Charlie,

I think I found a bug in the translation. As you can see the countrys are not translated. Double checked my options, but I have a picture for you. 
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/7109720/0d07b8ee-e1a4-11e4-97a0-c6660438fc58.JPG)
![unbenannt1](https://cloud.githubusercontent.com/assets/9327486/7109722/1bd5251e-e1a4-11e4-853d-e05242e83493.JPG)
Cheers,
Mario

PS: You do a great job. ;) Needed to say.

**Comment by CaerCam** [comment]
Makes sense: there's a POT file for countries and languages, but no german version: https://github.com/wpmovielibrary/wpmovielibrary/blob/master/languages/wpmovielibrary-iso-en_EN.po That's why countries/languages are shown in English.

I'll try to generate a translation from crawling some online dictionnary so that you can control and amend, it'll be quicker than manually translating the list :)

**Comment by CaerCam** [comment]
Uploaded, please review ;-)

**Comment by stargatehome** [comment]
Works great! :D Thanks. But there is one little issue: When you're hovering over a flag it shows as a title still the english version (wasn't able to screenshot that in a real way :/)
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/7128521/9bf84438-e253-11e4-95e8-d2cabe6a5cf6.JPG)

**Comment by CaerCam** [comment]
_It's not a bug, it's a feature!_ It's actually meant to be that way ;-) The idea is that people visiting your site may not speak German (or any other language for that matter) fluently, so the countries/languages label can be translated while the flag shows a more standard, English label.

**Comment by stargatehome** [comment]
Hey Charlie, oh now I understand. But could you ad an option to disable that title, so that only the country is shown up?
