### ISSUE TITLE
Search movie by author

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#264]
Unconfirmed, but search seem to not return movies when searched by their author. See https://wordpress.org/support/topic/multiple-authors-14?replies=6#post-6828515

**Comment by kutluhanaykut** [comment]
ı am using search everthing plugin.. adds all of the custom field data..

**Comment by stargatehome** [comment]
Yeah, you're quiet sure. The search not includes movies. :/

**Comment by kutluhanaykut** [comment]
actually i want to search everthing because the user may know an actors name, or something from the movie summary.. so search everything plugin solves my issues...

And i think importing movie data and updating it... and to keep it uptodate and correct is more important than 'search'.. for wpmolly plugin..

There are lots of other search plugins to create filters and search other than wpmolly

so i suggest to keep focused on data mining and update issues for wpmolly currently..
