### ISSUE TITLE
What's going on? :)

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#267]
Hey Charlie,

Do you have a short report on what's your actually working on and when you'll updating the plugin next time. :) Waiting for new great feauters. :) By the way: German Translation 2.0 is finished. :rotating_light: 

Cheers,
Mario

**Comment by CaerCam** [comment]
Not much, really :(

I've been under a huge amount of work for the last 4 or 5 weeks, so the development on the plugin has been very, very slow. Dev on version 2.2 is almost stopped because I need to get done with version 2.1.5 first, rebuilding the Grid is the current priority and I'll use what is done on that part to enhanced the Movies list in the dashboard. But it takes time… I also took a few days off to visit Sardinia last week, hence my silence, really needed some rest and fresh air. Now I'm back with a lot of motivation to keep my projects running :)

**Comment by stargatehome** [comment]
Great. :) As I always say, loving your work and will still help you to improve the plugin. ;)

**Comment by CaerCam** [comment]
Update!

I know it's been an awful while since anything's been done here, and for this I'm truly sorry. A couple of projects have been taking about all my time for the last months, and honestly, I'm kind of fed up with it. Tired of spending tens of hours of works on projects turned to garbage by witless clients.

Good news is! I should be done by then end of the week, with both projects. I then plan to take a few days of to get some sleep, go out and see friends, celebrate my birthday… And start again working on that beautiful project. I have tons of things I want to put in WPMovieLibrary, and have been prevented from doing for too long.

I plan to take the whole month of August to take over the development, maybe September too. I want version 2.1.5 out, with a renewed, JavaScript-powered grid. It will probably be a bit limited at first, but will gain in features once I'm sure the base works correctly. And when that's done, there's still a lot of work to put into version 2.2, which should be pretty fun and which I really miss working on :)
