### ISSUE TITLE
checking movie

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#270]
Hey Charlie,

would be great, if the plugin checks if the movie almost exist in the database, as you can see:
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/7781715/f0e56c04-00f4-11e5-9cc9-e808c216b930.JPG)

Cheers,
Mario

**Comment by CaerCam** [comment]
You mean, check if a movie has already been imported? It's already the case with the mass importer that should let you know which movies are already in your library and prevent creating unwanted duplicates.

It's not done when manually importing a movie, though, because at that point you should be able to import a movie twice if you want; a good clue is to check the permalink generated by WordPress in the editor: if you get `django-unchained-2` instead of `django-unchained`, you most likely have a duplicate.

That being said I guess some sort of warning could be useful, I'll think about it :-)

**Comment by stargatehome** [comment]
Great, a little hint would be nice. :) But thanks for the advice. ;)
