### ISSUE TITLE
Different view

### ISSUE THREAD

**Issue by koala-media** [wpmovielibrary/wpmovielibrary#281]
Hi there and thanks for a great plugin!
I have a question.. There is a movie "view" that i really like that only seems to show up in the backend..

In the dashboard, when i select "Your Library" i see a list of "Movies you recently added".
Clicking on the image of the movie shows up THE PERFECT way for me to display the movie in question... How to get this in the normal "page" ?

So when i select "Movies" from the top menu, i see the grid with movies, and when selecting a movie, that "Perfect view" shows instead of the standard one?

Also, the scraper seems to skip TV Shows... Can't it be made so that when i do a search on TV Shows it also shows the result? When i search on Breaking Bad, it doesn't show the TV Show... We then could make a checkbox or something to mark it Show or Movie

![perfect view](https://cloud.githubusercontent.com/assets/13199171/8521212/bf0d51f8-240b-11e5-9074-27b26ef6ac8c.PNG)

**Comment by CaerCam** [comment]
Hi koala-media,

You're right that view isn't available in public; it's a rather old view that never had a real purpose, now that I think about it, apart from a "cool" effect when you load the movie's dashboard… It will disappear on version 2.2 anyway. With version 2.1.5 the Grid will be rewritten, so it would be quite easy to implement this kind of view on the public side; that won't be a core feature, but I'll keep this in mind so that it can be done easily on the side :)

As for TV Shows, the plugin does not support them indeed. That's been a requested almost from the start, despite the fact that the plugin's named "WordPress __Movie__ Library" and not "WordPress __TVShow__ Library" :D I've planned for a long time to build an extension to add that support, but never got enough time yet…

**Comment by koala-media** [comment]
Thanks for your reply. At the moment I'm using newznab because it has both movie and TV support. As soon as TV support is implemented I will switch back to wpmovielibrary.

Sent from my iPad

On Jul 12, 2015, at 3:56 PM, Charlie Merland <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi koala-media,

You're right that view isn't available in public; it's a rather old view that never had a real purpose, now that I think about it, apart from a "cool" effect when you load the movie's dashboard... It will disappear on version 2.2 anyway. With version 2.1.5 the Grid will be rewritten, so it would be quite easy to implement this kind of view on the public side; that won't be a core feature, but I'll keep this in mind so that it can be done easily on the side :)

As for TV Shows, the plugin does not support them indeed. That's been a requested almost from the start, despite the fact that the plugin's named "WordPress Movie Library" and not "WordPress TVShow Library" :D I've planned for a long time to build an extension to add that support, but never got enough time yet...

-
