### ISSUE TITLE
Wrong actors permalink

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#431]
Report by @meugamer in https://github.com/wpmovielibrary/wpmovielibrary/issues/428#issuecomment-421055512.

**Comment by meugamer** [comment]
I left the pattern first. And then I tried linking the permanent links and all the links appeared on the 404 error page ... instead of directing it to the site / wp / actor or collection, genre etc. As it is installed on my test site, it is redirected to: site / actor and the error happens. Or when I click on the actors' names on the movie page that was added, it simply links the actor's name to the movie as if it were a single URL. site / movie / actor-name and so on.

**Comment by CaerCam** [comment]
@meugamer Could you check if the last commit changes anything regarding your issue?
